/*
 * API Specification for Orchestrator
 * This is a API specification for Orchestrator module of Aricent Edge Compute solution.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@altran.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.capgemini.south_node_adapter.infrastructure.feign.model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class EnterpriseDetails {
  @SerializedName("enterpriseName")
  private String enterpriseName = null;

  @SerializedName("domainName")
  private String domainName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("regions")
  private List<EnterpriseDetailsRegions> regions = new ArrayList<EnterpriseDetailsRegions>();
}
