/*
 * API Specification for Orchestrator
 * This is a API specification for Orchestrator module of Aricent Edge Compute solution.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@altran.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.capgemini.south_node_adapter.infrastructure.feign.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class EnterpriseDetailsRequestedEdges {
	@SerializedName("edge")
	private String edge = null;

	@SerializedName("edgeName")
	private String edgeName = null;

	@SerializedName("dnsURL")
	private String dnsURL = null;

	@AllArgsConstructor
	@JsonAdapter(DnsTypeEnum.Adapter.class)
	public enum DnsTypeEnum {
		@SerializedName("COREDNS")
		COREDNS("COREDNS"), @SerializedName("ROUTE53")
		ROUTE53("ROUTE53");

		private String value;

		public String getValue() {
			return value;
		}

		public static DnsTypeEnum fromValue(String input) {
			for (DnsTypeEnum b : DnsTypeEnum.values()) {
				if (b.value.equals(input)) {
					return b;
				}
			}
			return null;
		}

		public static class Adapter extends TypeAdapter<DnsTypeEnum> {
			@Override
			public void write(final JsonWriter jsonWriter, final DnsTypeEnum enumeration) throws IOException {
				jsonWriter.value(String.valueOf(enumeration.getValue()));
			}

			@Override
			public DnsTypeEnum read(final JsonReader jsonReader) throws IOException {
				Object value = jsonReader.nextString();
				return DnsTypeEnum.fromValue((String) (value));
			}
		}
	}
	@SerializedName("dnsType")
	private DnsTypeEnum dnsType = null;

	@SerializedName("requestedRuntimes")
	private List<String> requestedRuntimes = new ArrayList<String>();
}
