apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-6g-xr
  labels:
    app: {{ .Release.Name }}-mongodb-6g-xr
spec:
  type: LoadBalancer
#  externalIPs:
#    - 10.6.71.75  # Especifica la IP estática aquí
  ports:
    - port: 27018        # Puerto expuesto fuera del clúster
      targetPort: 27017  # Este debe coincidir con el containerPort del Deployment
      name: mongodb-6g-xr
      nodePort: 30018    # Asigna el nodePort explícitamente
  selector:
    app: 6g-xr  # Asegúrate de que este selector coincida con el label en tu Deployment
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sn-adapter
  labels:
    app: {{ .Release.Name }}-sn-adapter
spec:
  type: LoadBalancer
#  externalIPs:
#    - 10.6.71.75  # Especifica la IP estática aquí
  ports:
    - port: 8081        # Puerto expuesto fuera del clúster
      targetPort: 8080  # Puerto del contenedor
      name: exist-port
      nodePort: 30081    # Asigna el nodePort explícitamente
  selector:
    app: 6g-xr  # Asegúrate de que este selector coincida con el label en tu Deployment
